url: https://alliages.github.io
#baseurl: /

# Site settings
title: PARIS CHANGE D'ERE, Vers la neutralité carbone en 2050
email: paris2050@elioth.fr
description: "Rapport complet de l'étude Paris change d'ère, vers la neutralité carbone par Elioth Egis Conseil Quattrolibri Mana 2016"
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Elioth
  pic: 1
  position: Raphael Ménard
  social:
    - title: twitter
      url: https://twitter.com/elioth
    - title: linkedin
      url: https://fr.linkedin.com/company/elioth
    - title: web
      url: http://elioth.com

- name: Egis Conseil
  pic: 2
  position: Sébastien Duprat
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Quattrolibri
  pic: 3
  position: Julien Dossier
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Mana
  pic: 4
  position: Stéphane Chevrier
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: vimeo
    url: xxxx
  - title: issuu
    url: zzzz

# Postal address (add as many lines as necessary)
address:
  - line: 4 rue dolores Ibarruri
  - line: 93188 Montreuil

# Build settings
markdown: kramdown
permalink: pretty